/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medicalrecordsystemfinal;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anton Joseph Cruz
 */
public class MRSMedicineRecords extends javax.swing.JFrame {

    /**
     * Creates new form MRSMedicineRecords
     */
    DefaultTableModel tbl;
    Connect con;
    User u;
    
    public MRSMedicineRecords() {
        initComponents();
    }
    
    public MRSMedicineRecords(User user) {
        initComponents();
        setLocationRelativeTo(null);
        tbl = (DefaultTableModel) medicineT.getModel();
        con = new Connect();
        u = user;
        displayTable();
    }
    
    public void displayTable(){
        ArrayList<Medicine> ver = con.getMedicine();
        tbl.setRowCount(0);
        for(Medicine v : ver){
            String data[]={v.getGenericName(),v.getBrand(),v.getDosage()};
            tbl.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicineP = new javax.swing.JPanel();
        BackB = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        medicineT = new javax.swing.JTable();
        titleL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        medicineP.setBackground(new java.awt.Color(255, 255, 255));

        BackB.setBackground(new java.awt.Color(255, 0, 0));
        BackB.setForeground(new java.awt.Color(255, 255, 255));
        BackB.setText("Back");
        BackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBActionPerformed(evt);
            }
        });

        medicineT.setBackground(new java.awt.Color(255, 51, 51));
        medicineT.setForeground(new java.awt.Color(255, 255, 255));
        medicineT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Generic Name", "Brand", "Dosage"
            }
        ));
        medicineT.setSelectionBackground(new java.awt.Color(255, 153, 153));
        jScrollPane6.setViewportView(medicineT);

        titleL.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        titleL.setForeground(new java.awt.Color(0, 0, 0));
        titleL.setText("MEDICINE RECORD");

        javax.swing.GroupLayout medicinePLayout = new javax.swing.GroupLayout(medicineP);
        medicineP.setLayout(medicinePLayout);
        medicinePLayout.setHorizontalGroup(
            medicinePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicinePLayout.createSequentialGroup()
                .addGroup(medicinePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(medicinePLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BackB, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(medicinePLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(medicinePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleL, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        medicinePLayout.setVerticalGroup(
            medicinePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicinePLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titleL, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(BackB)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(medicineP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(medicineP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBActionPerformed
        // TODO add your handling code here:
        MRSMain main = new MRSMain(u);
        main.show();
        this.dispose();
    }//GEN-LAST:event_BackBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MRSMedicineRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MRSMedicineRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MRSMedicineRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MRSMedicineRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MRSMedicineRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackB;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel medicineP;
    private javax.swing.JTable medicineT;
    private javax.swing.JLabel titleL;
    // End of variables declaration//GEN-END:variables
}
