/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package medicalrecordsystemfinal;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anton Joseph Cruz
 */
public class MRSMain extends javax.swing.JFrame {

    /**
     * Creates new form MRSMain
     */
    Connect con;
    User u;
    DefaultTableModel tbl1;
    DefaultTableModel tbl2;
    String name;
    
    public MRSMain(User user) {
        initComponents();
        setLocationRelativeTo(null);
        con = new Connect();
        u = user;
        tbl1 = (DefaultTableModel) tblOnTreatment.getModel();
        tbl2 = (DefaultTableModel) tblTreated.getModel();
        name = user.getFirstname().trim() + " " + user.getLastname().trim();
        lblUsertype.setText(user.getUserType());
        lblName.setText(name);
        displayTable(name, user.getUserType(),1);
        displayTable(name, user.getUserType(),2);
    }

    private MRSMain() {}

    public final void displayTable(String name, String userType, int table){
        ArrayList<PatientInfo> pat;
        if (table == 1) {
            pat = con.getPatients(name, userType, 0);
            for (PatientInfo p : pat) {
                String data[] = {Integer.toString(p.getId()), p.getName(), p.getDoctor(), p.getNurse()};
                tbl1.addRow(data);
            }
        } else {
            pat = con.getPatients(name, userType, 1);
            for (PatientInfo p : pat) {
                String data[] = {Integer.toString(p.getId()), p.getName(), p.getDoctor(), p.getNurse()};
                tbl2.addRow(data);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTreated = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOnTreatment = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        medicineB = new javax.swing.JButton();
        nurseB = new javax.swing.JButton();
        doctorB = new javax.swing.JButton();
        addPatientInfoB = new javax.swing.JButton();
        UsernameL = new javax.swing.JLabel();
        lblUsertype = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("PATIENTS");

        tblTreated.setBackground(new java.awt.Color(255, 51, 51));
        tblTreated.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Name", "Doctor", "Nurse"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTreated.setSelectionBackground(new java.awt.Color(255, 153, 153));
        tblTreated.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTreatedMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTreated);
        if (tblTreated.getColumnModel().getColumnCount() > 0) {
            tblTreated.getColumnModel().getColumn(0).setResizable(false);
            tblTreated.getColumnModel().getColumn(1).setResizable(false);
            tblTreated.getColumnModel().getColumn(2).setResizable(false);
            tblTreated.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Treated");

        tblOnTreatment.setBackground(new java.awt.Color(255, 51, 51));
        tblOnTreatment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Name", "Doctor", "Nurse"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOnTreatment.setSelectionBackground(new java.awt.Color(255, 153, 153));
        tblOnTreatment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOnTreatmentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblOnTreatment);
        if (tblOnTreatment.getColumnModel().getColumnCount() > 0) {
            tblOnTreatment.getColumnModel().getColumn(0).setResizable(false);
            tblOnTreatment.getColumnModel().getColumn(1).setResizable(false);
            tblOnTreatment.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("On Treatment");

        medicineB.setBackground(new java.awt.Color(255, 51, 51));
        medicineB.setForeground(new java.awt.Color(255, 255, 255));
        medicineB.setText("Medicine Records");
        medicineB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineBActionPerformed(evt);
            }
        });

        nurseB.setBackground(new java.awt.Color(255, 51, 51));
        nurseB.setForeground(new java.awt.Color(255, 255, 255));
        nurseB.setText("Nurse List");
        nurseB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseBActionPerformed(evt);
            }
        });

        doctorB.setBackground(new java.awt.Color(255, 51, 51));
        doctorB.setForeground(new java.awt.Color(255, 255, 255));
        doctorB.setText("Doctor List");
        doctorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorBActionPerformed(evt);
            }
        });

        addPatientInfoB.setBackground(new java.awt.Color(255, 51, 51));
        addPatientInfoB.setForeground(new java.awt.Color(255, 255, 255));
        addPatientInfoB.setText("Add Patient Info");
        addPatientInfoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientInfoBActionPerformed(evt);
            }
        });

        UsernameL.setText("Welcome");

        lblUsertype.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsertype.setText("UserType");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Name");

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("← Logout");
        btnLogout.setBorder(null);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UsernameL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsertype)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(doctorB)
                                .addGap(18, 18, 18)
                                .addComponent(nurseB)
                                .addGap(18, 18, 18)
                                .addComponent(medicineB)
                                .addGap(18, 18, 18)
                                .addComponent(addPatientInfoB)))
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsertype)
                            .addComponent(UsernameL)
                            .addComponent(lblName))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicineB)
                    .addComponent(nurseB)
                    .addComponent(doctorB)
                    .addComponent(addPatientInfoB)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTreatedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTreatedMouseClicked
        // TODO add your handling code here:
        int index = tblOnTreatment.getSelectedRow();

        int id = Integer.parseInt(((String) tblOnTreatment.getValueAt(index, 0)));

        MRSPatientInfo mrs = new MRSPatientInfo(u, id);
        mrs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tblTreatedMouseClicked

    private void tblOnTreatmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOnTreatmentMouseClicked
        // TODO add your handling code here:
        int index = tblOnTreatment.getSelectedRow();

        int id = Integer.parseInt(((String) tblOnTreatment.getValueAt(index, 0)));

        MRSPatientInfo mrs = new MRSPatientInfo(u, id);
        mrs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tblOnTreatmentMouseClicked

    private void medicineBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineBActionPerformed
        // TODO add your handling code here:
        MRSMedicineRecords mrs = new MRSMedicineRecords(u);
        mrs.show();
        this.dispose();
    }//GEN-LAST:event_medicineBActionPerformed

    private void nurseBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseBActionPerformed
        // TODO add your handling code here:
        MRSNurse mrs = new MRSNurse(u);
        mrs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nurseBActionPerformed

    private void doctorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorBActionPerformed
        // TODO add your handling code here:
        MRSDoctors mrs = new MRSDoctors(u);
        mrs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_doctorBActionPerformed

    private void addPatientInfoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientInfoBActionPerformed
        // TODO add your handling code here:
        MRSAddPatientInfo mrs = new MRSAddPatientInfo(u);
        mrs.show();
        this.dispose();
    }//GEN-LAST:event_addPatientInfoBActionPerformed

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        MRSLogin login = new MRSLogin();
        login.show();
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MRSMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MRSMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MRSMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MRSMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MRSMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UsernameL;
    private javax.swing.JButton addPatientInfoB;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton doctorB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblUsertype;
    private javax.swing.JButton medicineB;
    private javax.swing.JButton nurseB;
    private javax.swing.JTable tblOnTreatment;
    private javax.swing.JTable tblTreated;
    // End of variables declaration//GEN-END:variables
}
